fix: can't get the CSRF token
Root cause:
Use the research API can't get CSRF.
It will raise the below error:
```
yarn run v1.22.10
$ node app.js
/Users/zephyr/Documents/Coding/dummy/rentHouse/lib/getToken.js:9
  const csrfToken = regExp.exec(response.body)[1];
                                              ^

TypeError: Cannot read properties of null (reading '1')
    at module.exports (/Users/zephyr/Documents/Coding/dummy/rentHouse/lib/getToken.js:9:47)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/Users/zephyr/Documents/Coding/dummy/rentHouse/lib/getFirstPostId.js:6:22)
    at async /Users/zephyr/Documents/Coding/dummy/rentHouse/app.js:11:22

Node.js v17.5.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Solution: change the fetching site to the 591 index URL.